name: Go Build

permissions:
  contents: write

on:
  push:
    branches:
      - main   # Trigger on commits to main branch
  workflow_dispatch: # Optional manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        go: [1.21]  # Replace with your desired Go version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build binary
        run: |
          OS=${{ matrix.os }}
          EXT=""
          if [ "$OS" = "windows" ]; then EXT=".exe"; fi
          mkdir -p build
          go build -o build/reasm-$OS$EXT

      - name: Upload artifact for commits
        if: github.event_name == 'push' && github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: reasm-${{ matrix.os }}
          path: build/reasm-${{ matrix.os }}*
